version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "coworking-analytics"  # Replace with your ECR repository name
    AWS_REGION: "us-east-1"  # Replace with your AWS region

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 825222744444.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER ./analytics/
      - docker images  # List Docker images to verify the image was built
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER 825222744444.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 825222744444.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
artifacts:
  files:
    - '**/*'
