apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-db-details  # Adjusted to comply with naming rules
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: bXlwYXNzd29yZA==
